# Generated by Django 4.0.1 on 2022-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mysaia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port1', models.CharField(max_length=1000)),
                ('port2', models.CharField(max_length=1000)),
                ('export', models.CharField(max_length=1000)),
            ],
        ),
    ]
